const lang = {
    en: {
        signin: "Sign In",
        signup: "Sign Up",
        fullNamePlaceholder: "Full name",
        emailAddressPlaceholder: "Email address",
        passwordPlaceholder: "Password",
        signinMessage: "New to Netflix? Sign up now.",
        signupMessage: "Already registered? Sign in now.",
        gptSearch: "GPT Search",
        home: "Home page",
        signout: "Sign Out",
        play: "Play",
        moreInfo: "More Info",
        nowPlaying: "Now Playing",
        popular: "Popular",
        topRated: "Top Rated",
        upcoming: "Upcoming",
        gptSearchPlaceholder: "What would you like to watch today?",
        tmdbSearch: "Search",
    },

    hi: {
        signin: "दाखिल करना",
        signup: "साइन अप करें",
        fullNamePlaceholder: "पूरा नाम",
        emailAddressPlaceholder: "मेल पता",
        passwordPlaceholder: "पासवर्ड",
        signinMessage: "नेटफ्लिक्स पर नए हैं? अभी साइनअप करें।",
        signupMessage: "पहले से ही पंजीकृत? अब साइन इन करो।",
        gptSearch: "जीपीटी खोज",
        home: "होम पेज",
        signout: "साइन आउट",
        play: "देखना",
        moreInfo: "और जानकारी",
        nowPlaying: "अब खेल रहे हैं",
        popular: "लोकप्रिय",
        topRated: "टॉप रेटेड",
        upcoming: "आने वाली फिल्में",
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
        tmdbSearch: "खोज",
    },

    te: {
        signin: "సైన్ ఇన్ అవండి",
        signup: "సైన్ అప్ చేయండి",
        fullNamePlaceholder: "పూర్తి పేరు",
        emailAddressPlaceholder: "ఇమెయిల్ చిరునామా",
        passwordPlaceholder: "పాస్వర్డ్",
        signinMessage: "Netflixకి కొత్త? ఇప్పుడే సైన్ అప్ చేయండి.",
        signupMessage: "ముందే నమోదు అయ్యారా? ఇప్పుడే సైన్ ఇన్ అవండి.",
        gptSearch: "GPT శోధన",
        home: "హోమ్ పేజీ",
        signout: "సైన్ అవుట్",
        play: "వీక్షించు",
        moreInfo: "మరింత సమాచారం",
        nowPlaying: "ఇప్పుడు ఆడుతున్నవి",
        popular: "జనాదరణ పొందినవి",
        topRated: "టాప్ రేటింగ్",
        upcoming: "రాబోయే సినిమాలు",
        gptSearchPlaceholder: "మీరు ఈరోజు ఏమి చూడాలనుకుంటున్నారు?",
        tmdbSearch: "అన్వేషించు",
    },

    ta: {
        signin: "உள்நுழைக",
        signup: "பதிவு செய்யவும்",
        fullNamePlaceholder: "முழு பெயர்",
        emailAddressPlaceholder: "மின்னஞ்சல் முகவரி",
        passwordPlaceholder: "கடவுச்சொல்",
        signinMessage: "Netflix க்கு புதியவரா? இப்பொது பதிவு செய்.",
        signupMessage: "ஏற்கனவே பதிவு செய்யப்பட்டது? இப்போது உள்நுழையவும்.",
        gptSearch: "GPT தேடல்",
        home: "முகப்பு பக்கம்",
        signout: "வெளியேறு",
        play: "பார்வை",
        moreInfo: "மேலும் தகவல்",
        nowPlaying: "தற்பொழுது விளையாடி கொண்டிருக்கிறேன்",
        popular: "பிரபலமான",
        topRated: "சிறந்த மதிப்பிடப்பட்டது",
        upcoming: "வரவிருக்கும் திரைப்படங்கள்",
        gptSearchPlaceholder: "இன்று நீங்கள் எதைப் பார்க்க விரும்புகிறீர்கள்?",
        tmdbSearch: "தேடல்",
    },

    ka: {
        signin : "ಸೈನ್ ಇನ್ ಮಾಡಿ",
        signup: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
        fullNamePlaceholder: "ಪೂರ್ಣ ಹೆಸರು",
        emailAddressPlaceholder: "ಇಮೇಲ್ ವಿಳಾಸ",
        passwordPlaceholder: "ಗುಪ್ತಪದ",
        signinMessage: "Netflix ಗೆ ಹೊಸಬರೇ? ಈಗ ಸೈನ್ ಅಪ್ ಮಾಡಿ.",
        signupMessage: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ? ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
        gptSearch: "GPT ಹುಡುಕಾಟ",
        home: "ಮುಖಪುಟ",
        signout: "ಸೈನ್ ಔಟ್",
        play: "ನೋಟ",
        moreInfo: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ",
        nowPlaying: "ಈಗ ಪ್ರದರ್ಶಿಸಲ್ಪಡುತ್ತಿದೆ",
        popular: "ಜನಪ್ರಿಯ",
        topRated: "ಅತ್ಯುತ್ತಮವಾದ",
        upcoming: "ಮುಂಬರುವ ಚಲನಚಿತ್ರಗಳು",
        gptSearchPlaceholder: "ನೀವು ಇಂದು ಏನನ್ನು ವೀಕ್ಷಿಸಲು ಬಯಸುತ್ತೀರಿ?",
        tmdbSearch: "ಹುಡುಕಿ",
    },
    
    ma: {
        signin: "സൈൻ ഇൻ",
        signup: "സൈൻ അപ്പ് ചെയ്യുക",
        fullNamePlaceholder: "പൂർണ്ണമായ പേര്",
        emailAddressPlaceholder: "ഇമെയിൽ വിലാസം",
        passwordPlaceholder: "പാസ്വേഡ്",
        signinMessage: "Netflix-ൽ പുതിയ ആളാണോ? ഇപ്പോൾ സൈൻ അപ്പ് ചെയ്യുക.",
        signupMessage: "ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ടോ? ഇപ്പോൾ സൈൻ ഇൻ ചെയ്യുക.",
        gptSearch: "GPT തിരയൽ",
        home: "ഹോം പേജ്",
        signout: "സൈൻ ഔട്ട്",
        play: "കാഴ്ച",
        moreInfo: "കൂടുതൽ വിവരങ്ങൾ",
        nowPlaying: "ഇപ്പോൾ കളിക്കുന്നു",
        popular: "ജനകീയമായ",
        topRated: "ഉയർന്ന റേറ്റുചെയ്തത്",
        upcoming: "വരാനിരിക്കുന്ന സിനിമകൾ",
        gptSearchPlaceholder: "ഇന്ന് നിങ്ങൾ എന്താണ് കാണാൻ ആഗ്രഹിക്കുന്നത്?",
        tmdbSearch: "തിരയുക",
    }
};

export default lang;